---
title: 小雅的博客
email: chenxiaoyamail@gmail.com
description: '记录我的点点滴滴

'
baseurl: ''
url: http://chenxiaoya.github.io
twitter_username: 
github_username: chenxiaoya
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
