---
title: 小雅的博客
description: '记录我的点点滴滴'
baseurl: ''
twitter_username: 
github_username: chenxiaoya
url: http://chenxiaoya.github.io
email: chenxiaoyamail@gmail.com
markdown: kramdown
theme: minima
intensedebate_comments: true
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
